CREATE TABLE `subject` (
  `id` BIGINT(20) NOT NULL,
  `course` VARCHAR(255) DEFAULT NULL,
  `lecturer` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=UTF8MB4 DEFAULT COLLATE=UTF8MB4_GENERAL_CI;

